export default {
  UNAUTHORIZED: "UNAUTHORIZED",
  REGISTRATION_FAILED: "REGISTRATION FAILED",
  TOKEN_EXPIRED: "TOKEN EXPIRED",
  INTERNAL_ERROR: "INTERNAL ERROR",
  BAD_REQUEST: "BAD REQUEST",
  USER_ALREADY_EXISTS: "USER ALREADY EXISTS",
  USER_UPDATE_FAILED: "USER UPDATE FAILED",
  DATA_UPDATE_FAILED: "DATA UPDATE FAILED",
  PERMISSION_DENIED: "PERMISSION DENIED",
  INVALID_TOKEN: "INVALID TOKEN",
  INVALID_TYPE: "INVALID TYPE",
  ALREADY_EXIST: "ALREADY EXIST",
};
