export default {
  SUCCESSFULLY_AUTHORIZED: "SUCCESSFULLY AUTHORIZED",
  SUCCESSFULLY_USER_CREATED: "SUCCESSFULLY USER CREATED",
  SUCCESSFULLY_USER_UPDATED: "SUCCESSFULLY USER UPDATED",
  SUCCESSFULLY_USER_DELETED: "SUCCESSFULLY USER DELETED",
  SUCCESSFULLY_DATA_RETRIVED: "SUCCESSFULLY DATA RETRIEVED",
  SUCCESSFULLY_DATA_ADDED: "SUCCESSFULLY DATA ADDED",
  SUCCESSFULLY_DATA_UPDATED: "SUCCESSFULLY DATA UPDATED",
  SUCCESSFULLY_DATA_DELETED: "SUCCESSFULLY DATA DELETED",
};
